name: Test Lando

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test Lando
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Setup Lando
      uses: lando/setup-lando@v3
    - name: Add pressbooks.test to hosts file
      run: |
        sudo echo "127.0.0.1 pressbooks.test" | sudo tee -a /etc/hosts
    - name: Configure environment
      run: |
        cp .env.example .env && \
        echo 'ARCHITECTURE=arm64' >> config_services/.env
    - name: Start Lando
      run: |
        lando start
    - name: Import database
      run: |
        lando db-import pb_local_db.sql && \
    - name: Install hurl
      uses: gacts/install-hurl@v1
    - name: Run hurl tests
      run: |
        hurl test.hurl
    - name: Install and run tests
      run: |
        lando install-tests && \
        lando test
    - name: Stop Lando
      run: |
        lando stop
